### ISSUE TITLE
Order ID Type Alias

### ISSUE THREAD

**Issue by jalandis** [plutov/paypal#198]
I recently misinterpreted Paypal documentation causing me to treat the ID field for a capture response as a unique identifier for the capture event and not the order id.  It occurs to me that this type of mistake would be harder to make if instead of strings the responses had type aliases defined.  

For instance:
```
type OrderID string

// CaptureOrderResponse is the response for capture order
CaptureOrderResponse struct {
	ID            OrderID                 `json:"id,omitempty"`
	Status        string                 `json:"status,omitempty"`
	Payer         *PayerWithNameAndPhone `json:"payer,omitempty"`
	Address       *Address               `json:"address,omitempty"`
	PurchaseUnits []CapturedPurchaseUnit `json:"purchase_units,omitempty"`
}
```

This would help the code be more self-documenting and hopefully prevent the issue I ran into.  I am interested to hear your thoughts or suggestions on this?

If it's acceptable,  I would be happy to prep a PR targeting all order id fields in the defined payloads and swap with this new type.

**Comment by thomasf** [comment]
It's not backwards compatible though so it breaks the semantic versioning. A lot of recent changes seems to have done this so I guess that minor breaking changes are accepted in this project.

This is kind of a big change (like major version) because if this change were to be added it should be added for every single string id type so it would affect more or less all structs. Only targeting order id and no other ID string types makes no sense will contribute to making the package API more confusing.

**Comment by thomasf** [comment]
Personally I don't think that this is worth it.

* All PayPal API work requires you to read and understand the PayPal API documentation
* It can become tedious having to deal with lots of extra string types for users of this package.
* Not having to do a major version bump just because of this change also IMO speaks against it, I don't think the utility is worth the cost. 

I also believe that in most situations people will catch issues like this rather quickly while writing tests or working in development mode against the PayPal sandbox when they see that IDs don't match up.

**Comment by plutov** [comment]
Thanks for highlighting this. I agree with @thomasf that type aliases would be too much for this package. Though, looking at your example, simply changing field name from ID to OrderID should be more clear to the users of this package.

**Comment by jalandis** [comment]
@plutov I appreciate the feedback and the project your maintaining!  If the extra types are not helpful then I have no objections to closing this issue.
